
fibo1:
	pipenv run python3 ./src/main.py fib

fibo2:
	pipenv run python3 ./src/main.py fib2

closure11:
	pipenv run python3 ./src/main.py closure1 

closure22:
	pipenv run python3 ./src/main.py closure2

test: 
	pipenv run pytest tests/


run: 
	pipenv run python3 ./src/main.py input

expr_script:
	pipenv run python3 ./src/expr_script.py ./src/expression.py

stmt_script:
	pipenv run python3 ./src/stmt_script.py ./src/stmt.py

