
i:
	gcc -o main main.c chunk.c memory.c debug.c value.c vm.c compiler.c scanner.c object.c table.c  && ./main input

c:
	gcc -o main main.c chunk.c memory.c debug.c value.c vm.c compiler.c scanner.c object.c table.c 

r:
	gcc -o main main.c chunk.c memory.c debug.c value.c vm.c compiler.c scanner.c object.c table.c && ./main
